name: Packer Build

on:
  push:
    branches:
      - main

jobs:
  packer-build:
    runs-on: ubuntu-20.04
    environment: gcp
    steps:
      - name: Checkout Packer project
        uses: actions/checkout@v3

      - name: Initialize Packer Plugin Binaries:GCP
        run: packer init ./gcp

      - name: Build Image:GCP
        env:
          PKR_VAR_project: ${{ secrets.GOOGLE_PROJECT }}
          GOOGLE_APPLICATION_CREDENTIALS: gcp.json
        run: |
          cat > $GOOGLE_APPLICATION_CREDENTIALS << EOF
          ${{ secrets.GOOGLE_CREDENTIALS }}
          EOF
          trap "rm -f $GOOGLE_APPLICATION_CREDENTIALS" EXIT
          packer build -force ./gcp

      - name: Initialize Packer Plugin Binaries:AWS
        run: packer init ./aws

      - name: Build Image:AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          packer build -var-file=./aws/amd64.pkrvars.hcl ./aws
          packer build -var-file=./aws/arm64.pkrvars.hcl ./aws