name: lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initialize Packer Plugin Binaries:GCP
        run: packer init ./gcp

      - name: Validate Template:GCP
        env:
          PKR_VAR_project: dummy_value
        run: packer validate ./gcp
        
      - name: Initialize Packer Plugin Binaries:AWS
        run: packer init ./aws

      - name: Validate Template:AWS
        env:
          PKR_VAR_project: dummy_value
        run: packer validate ./aws