name: lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Switch to GCP
        run: cd gcp

      - name: Initialize Packer Plugin Binaries:GCP
        run: packer init .

      - name: Validate Template:GCP
        env:
          PKR_VAR_project: dummy_value
        run: packer validate .

      - name: Switch to AWS
        run: cd ../aws
        
      - name: Initialize Packer Plugin Binaries:AWS
        run: packer init .

      - name: Validate Template:AWS
        env:
          PKR_VAR_project: dummy_value
        run: packer validate .